# Generated by Django 3.2.16 on 2022-12-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='wallet_number',
            field=models.IntegerField(null=True),
        ),
    ]
