# Generated by Django 3.2.16 on 2023-01-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='totall_payment',
            new_name='total_payment',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
